apiVersion: v1
kind: Service
metadata:
  name: luazai-api
  labels:
    app: luazai
    component: api
spec:
  type: ClusterIP
  selector:
    app: luazai
    component: api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
